// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./../src/views/exception/403.vue')['default']
    404: typeof import('./../src/views/exception/404.vue')['default']
    500: typeof import('./../src/views/exception/500.vue')['default']
    About: typeof import('./../src/views/about/index.vue')['default']
    ExceptionBase: typeof import('./../src/components/exception/ExceptionBase.vue')['default']
    IconCustomNoPermission: typeof import('~icons/custom/no-permission')['default']
    IconCustomNotFound: typeof import('~icons/custom/not-found')['default']
    IconCustomServiceError: typeof import('~icons/custom/service-error')['default']
    ParentLayout: typeof import('./../src/layout/parentLayout.vue')['default']
    Undefined: typeof import('./../src/layout/index.vue')['default']
  }
}

export { }
